CREATE TYPE weather_status AS ENUM ('STRONGRAIN',
    'STRONGWIND',
    'MEDIUMRAIN',
    'MEDIUMWIND',
    'LOWRAIN',
    'LOWWIND',
    'NORAIN');

CREATE TABLE flight(
    flight_id int PRIMARY KEY GENERATED BY DEFAULT,
    departureTime TIMESTAMP WITH TIME ZONE,
    arrival_time TIMESTAMP WITH TIME ZONE,
    from_airport VARCHAR(255),
    to_airport VARCHAR(255)
);

CREATE table air_plane(
    airplane_id int PRIMARY KEY GENERATED BY DEFAULT ,
    plane_name VARCHAR(255),
    air_plane_model VARCHAR(255),
    air_plane_status VARCHAR(255),
    long_of_way int,
    flight_id int UNIQUE,
    CONSTRAINT fk_air_plane_flight FOREIGN KEY (flight_id) REFERENCES flight(flight_id)
);

CREATE table flight_crew(
    crew_id int PRIMARY KEY GENERATED BY DEFAULT,
    crew_name VARCHAR(255),
    crew_status VARCHAR(255),
    crew_age int,
    crew_sex VARCHAR(50),
    crew_post VARCHAR(255)
    flight_id int,
    CONSTRAINT fk_flight_crew_flight FOREIGN KEY (flight_id) REFERENCES flight(flight_id)
);

CREATE table airport(
    id int PRIMARY KEY GENERATED BY DEFAULT,
    airport_name VARCHAR(255),
    country VARCHAR(255),
    weather_status weather_status
);

CREATE TYPE airplane_status AS ENUM('FREE','ASSIGNED');